name: test

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-23.11
        extra_nix_config: |
          extra-platforms = aarch64-linux riscv64-linux i686-linux
    - uses: DeterminateSystems/magic-nix-cache-action@v13

    - run: ./.github/build.sh
